# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-setup-atmos
  description: A GitHub Actions that installs the Atmos CLI
  homepage: https://cloudposse.com/accelerate
  topics: ""
