name: auto-release

on:
  push:
    branches:
      - main
      - master
      - production

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/github-action-auto-release@v2
        with:
          publish: false
          prerelease: false
          config-name: auto-release.yml          
