name: Test Downloading Atmos
on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: [
      "runs-on=${{ github.run_id }}",
      "runner=2cpu-linux-x64",
    ]
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        id: latest
        with:
          # default, but explicit for clarity
          atmos-version: 'latest'
      - uses: ./
        id: rc
        with:
          atmos-version: 'v1.172.0-rc.1'
      - uses: ./
        id: full-release
        with:
          atmos-version: 'v1.172.0'
      - uses: ./
        id: semver-constraint
        with:
          atmos-version: '<=1.172.0'

    outputs:
      latest: "${{ steps.latest.outputs.atmos-version }}"
      rc: "${{ steps.rc.outputs.atmos-version }}"
      full-release: "${{ steps.full-release.outputs.atmos-version }}"
      semver-constraint: "${{ steps.semver-constraint.outputs.atmos-version }}"

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v1
        with:
          expected: 'rc'
          actual: "${{ needs.test.outputs.latest }}"
          comparison: 'notContains'
      - uses: nick-fields/assert-action@v1
        with:
          expected: 'v1.172.0'
          actual: "${{ needs.test.outputs.full-release }}"
          comparison: 'exact'
      - uses: nick-fields/assert-action@v1
        with:
          expected: 'v1.172.0'
          actual: "${{ needs.test.outputs.semver-constraint }}"
          comparison: 'exact'
      - uses: nick-fields/assert-action@v1
        with:
          expected: 'v1.172.0-rc.1'
          actual: "${{ needs.test.outputs.rc }}"
          comparison: 'exact'