name: Test example positive
on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: [
      "runs-on=${{ github.run_id }}",
      "runner=2cpu-linux-x64",
    ]
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        id: current


    outputs:
      result: "${{ steps.current.outputs.atmos-version }}"

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v1
        with:
          expected: 'true'
          actual: "${{ needs.test.outputs.result }}"